name: test pr event results
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  echo-event-results:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event results
        run: echo "${{ github.event.pull_request.merged }} ${{ github.event.pull_request.head.ref }}"
